version: '3.8'
services:
  springboot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: springboot
    ports:
      - "8080:8080"
    volumes:
      - ~/.aws:/root/.aws:ro # Mount the AWS credentials if needed
